package lcs.prs.goingmobile.entities;
// Generated Aug 19, 2016 11:55:51 AM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clients generated by hbm2java
 */
@Entity
@Table(name = "clients", catalog = "goingmobile")
public class Clients implements java.io.Serializable {

	private Integer id;
	private String username;
	private String email;
	private String firstName;
	private String lastName;
	private String password;
	private boolean isActive;
	private Date registrationDate;
	private String profilePicture;
	private float kmsTotal;
	private double gmPointsTotal;
	private double gmPointsHistoryCumul;
	private float kmsHistoryCumul;
	private String bonus;
	private Boolean isPublic;
	private Set<Addresses> addresseses = new HashSet<Addresses>(0);
	private Set<Journeys> journeyses = new HashSet<Journeys>(0);
	private Set<Transactions> transactionses = new HashSet<Transactions>(0);

	public Clients() {
	}

	public Clients(String username, String email, String firstName, String lastName, String password, boolean isActive,
			Date registrationDate, float kmsTotal, double gmPointsTotal, double gmPointsHistoryCumul,
			float kmsHistoryCumul) {
		this.username = username;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.isActive = isActive;
		this.registrationDate = registrationDate;
		this.kmsTotal = kmsTotal;
		this.gmPointsTotal = gmPointsTotal;
		this.gmPointsHistoryCumul = gmPointsHistoryCumul;
		this.kmsHistoryCumul = kmsHistoryCumul;
	}

	public Clients(String username, String email, String firstName, String lastName, String password, boolean isActive,
			Date registrationDate, String profilePicture, float kmsTotal, double gmPointsTotal,
			double gmPointsHistoryCumul, float kmsHistoryCumul, String bonus, Boolean isPublic,
			Set<Addresses> addresseses, Set<Journeys> journeyses, Set<Transactions> transactionses) {
		this.username = username;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.isActive = isActive;
		this.registrationDate = registrationDate;
		this.profilePicture = profilePicture;
		this.kmsTotal = kmsTotal;
		this.gmPointsTotal = gmPointsTotal;
		this.gmPointsHistoryCumul = gmPointsHistoryCumul;
		this.kmsHistoryCumul = kmsHistoryCumul;
		this.bonus = bonus;
		this.isPublic = isPublic;
		this.addresseses = addresseses;
		this.journeyses = journeyses;
		this.transactionses = transactionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "email", nullable = false, length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "firstName", nullable = false, length = 20)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 20)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "password", nullable = false, length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "isActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "registrationDate", nullable = false, length = 10)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Column(name = "profilePicture")
	public String getProfilePicture() {
		return this.profilePicture;
	}

	public void setProfilePicture(String profilePicture) {
		this.profilePicture = profilePicture;
	}

	@Column(name = "kmsTotal", nullable = false, precision = 12, scale = 0)
	public float getKmsTotal() {
		return this.kmsTotal;
	}

	public void setKmsTotal(float kmsTotal) {
		this.kmsTotal = kmsTotal;
	}

	@Column(name = "gmPointsTotal", nullable = false, precision = 22, scale = 0)
	public double getGmPointsTotal() {
		return this.gmPointsTotal;
	}

	public void setGmPointsTotal(double gmPointsTotal) {
		this.gmPointsTotal = gmPointsTotal;
	}

	@Column(name = "gmPointsHistoryCumul", nullable = false, precision = 22, scale = 0)
	public double getGmPointsHistoryCumul() {
		return this.gmPointsHistoryCumul;
	}

	public void setGmPointsHistoryCumul(double gmPointsHistoryCumul) {
		this.gmPointsHistoryCumul = gmPointsHistoryCumul;
	}

	@Column(name = "kmsHistoryCumul", nullable = false, precision = 12, scale = 0)
	public float getKmsHistoryCumul() {
		return this.kmsHistoryCumul;
	}

	public void setKmsHistoryCumul(float kmsHistoryCumul) {
		this.kmsHistoryCumul = kmsHistoryCumul;
	}

	@Column(name = "bonus", length = 20)
	public String getBonus() {
		return this.bonus;
	}

	public void setBonus(String bonus) {
		this.bonus = bonus;
	}

	@Column(name = "isPublic")
	public Boolean getIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(Boolean isPublic) {
		this.isPublic = isPublic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clients")
	public Set<Addresses> getAddresseses() {
		return this.addresseses;
	}

	public void setAddresseses(Set<Addresses> addresseses) {
		this.addresseses = addresseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clients")
	public Set<Journeys> getJourneyses() {
		return this.journeyses;
	}

	public void setJourneyses(Set<Journeys> journeyses) {
		this.journeyses = journeyses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clients")
	public Set<Transactions> getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set<Transactions> transactionses) {
		this.transactionses = transactionses;
	}

}
