package lcs.prs.goingmobile.entities;
// Generated Aug 19, 2016 11:55:51 AM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Partners generated by hbm2java
 */
@Entity
@Table(name = "partners", catalog = "goingmobile")
public class Partners implements java.io.Serializable {

	private Integer id;
	private String organizationName;
	private String organizationDescription;
	private Date registrationDate;
	private boolean isActive;
	private String profilePicture;
	private String vatNumber;
	private String username;
	private String password;
	private String accountLevel;
	private Set<Addresses> addresseses = new HashSet<Addresses>(0);
	private Set<Transactions> transactionses = new HashSet<Transactions>(0);
	private Set<Partnerads> partneradses = new HashSet<Partnerads>(0);

	public Partners() {
	}

	public Partners(String organizationName, String organizationDescription, Date registrationDate, boolean isActive,
			String vatNumber, String username, String password) {
		this.organizationName = organizationName;
		this.organizationDescription = organizationDescription;
		this.registrationDate = registrationDate;
		this.isActive = isActive;
		this.vatNumber = vatNumber;
		this.username = username;
		this.password = password;
	}

	public Partners(String organizationName, String organizationDescription, Date registrationDate, boolean isActive,
			String profilePicture, String vatNumber, String username, String password, String accountLevel,
			Set<Addresses> addresseses, Set<Transactions> transactionses, Set<Partnerads> partneradses) {
		this.organizationName = organizationName;
		this.organizationDescription = organizationDescription;
		this.registrationDate = registrationDate;
		this.isActive = isActive;
		this.profilePicture = profilePicture;
		this.vatNumber = vatNumber;
		this.username = username;
		this.password = password;
		this.accountLevel = accountLevel;
		this.addresseses = addresseses;
		this.transactionses = transactionses;
		this.partneradses = partneradses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "organizationName", nullable = false, length = 45)
	public String getOrganizationName() {
		return this.organizationName;
	}

	public void setOrganizationName(String organizationName) {
		this.organizationName = organizationName;
	}

	@Column(name = "organizationDescription", nullable = false, length = 65535)
	public String getOrganizationDescription() {
		return this.organizationDescription;
	}

	public void setOrganizationDescription(String organizationDescription) {
		this.organizationDescription = organizationDescription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "registrationDate", nullable = false, length = 10)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Column(name = "isActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "profilePicture")
	public String getProfilePicture() {
		return this.profilePicture;
	}

	public void setProfilePicture(String profilePicture) {
		this.profilePicture = profilePicture;
	}

	@Column(name = "vatNumber", nullable = false, length = 40)
	public String getVatNumber() {
		return this.vatNumber;
	}

	public void setVatNumber(String vatNumber) {
		this.vatNumber = vatNumber;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "accountLevel", length = 20)
	public String getAccountLevel() {
		return this.accountLevel;
	}

	public void setAccountLevel(String accountLevel) {
		this.accountLevel = accountLevel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partners")
	public Set<Addresses> getAddresseses() {
		return this.addresseses;
	}

	public void setAddresseses(Set<Addresses> addresseses) {
		this.addresseses = addresseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partners")
	public Set<Transactions> getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set<Transactions> transactionses) {
		this.transactionses = transactionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partners")
	public Set<Partnerads> getPartneradses() {
		return this.partneradses;
	}

	public void setPartneradses(Set<Partnerads> partneradses) {
		this.partneradses = partneradses;
	}

}
